apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: containerised-service-config
    literals:
      - SERVICE_NAME=containerised-service
      - APP_ENV=staging
      - LOG_LEVEL=INFO

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: deployment-environment.yaml
  - path: deployment-replica-count.yaml
